package uk.co.alteff4.mm.client.model;

// Date: 05/05/2013 20:45:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX








import net.minecraft.client.model.*;
import net.minecraft.entity.Entity;

public class modelAnvil extends ModelBase
{
  //fields
    ModelRenderer Back_Spike_21;
    ModelRenderer Base_1;
    ModelRenderer Base_2;
    ModelRenderer Stand;
    ModelRenderer Main_Section;
    ModelRenderer Front_Spike_1;
    ModelRenderer Front_Spike_2;
    ModelRenderer Back_Spike_23;
    ModelRenderer Back_Spike_22;
  
  public modelAnvil()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Back_Spike_21 = new ModelRenderer(this, 0, 0);
      Back_Spike_21.addBox(0F, 0F, 0F, 1, 1, 2);
      Back_Spike_21.setRotationPoint(7F, 18F, -1F);
      Back_Spike_21.setTextureSize(64, 32);
      Back_Spike_21.mirror = true;
      setRotation(Back_Spike_21, 0F, 0F, 0F);
      Base_1 = new ModelRenderer(this, 0, 0);
      Base_1.addBox(0F, 0F, 0F, 8, 2, 6);
      Base_1.setRotationPoint(-4F, 23F, -3F);
      Base_1.setTextureSize(64, 32);
      Base_1.mirror = true;
      setRotation(Base_1, 0F, 0F, 0F);
      Base_2 = new ModelRenderer(this, 0, 0);
      Base_2.addBox(0F, 0F, 0F, 6, 1, 4);
      Base_2.setRotationPoint(-3F, 22F, -2F);
      Base_2.setTextureSize(64, 32);
      Base_2.mirror = true;
      setRotation(Base_2, 0F, 0F, 0F);
      Stand = new ModelRenderer(this, 0, 0);
      Stand.addBox(0F, 0F, 0F, 4, 2, 2);
      Stand.setRotationPoint(-2F, 20F, -1F);
      Stand.setTextureSize(64, 32);
      Stand.mirror = true;
      setRotation(Stand, 0F, 0F, 0F);
      Main_Section = new ModelRenderer(this, 0, 0);
      Main_Section.addBox(0F, 0F, 0F, 8, 5, 6);
      Main_Section.setRotationPoint(-4F, 15F, -3F);
      Main_Section.setTextureSize(64, 32);
      Main_Section.mirror = true;
      setRotation(Main_Section, 0F, 0F, 0F);
      Front_Spike_1 = new ModelRenderer(this, 0, 0);
      Front_Spike_1.addBox(0F, 0F, 0F, 2, 1, 6);
      Front_Spike_1.setRotationPoint(-8F, 15F, -3F);
      Front_Spike_1.setTextureSize(64, 32);
      Front_Spike_1.mirror = true;
      setRotation(Front_Spike_1, 0F, 0F, 0F);
      Front_Spike_2 = new ModelRenderer(this, 0, 0);
      Front_Spike_2.addBox(0F, 0F, 0F, 2, 2, 6);
      Front_Spike_2.setRotationPoint(-6F, 15F, -3F);
      Front_Spike_2.setTextureSize(64, 32);
      Front_Spike_2.mirror = true;
      setRotation(Front_Spike_2, 0F, 0F, 0F);
      Back_Spike_22 = new ModelRenderer(this, 0, 0);
      Back_Spike_22.addBox(0F, 0F, 0F, 1, 4, 4);
      Back_Spike_22.setRotationPoint(4F, 16F, -2F);
      Back_Spike_22.setTextureSize(64, 32);
      Back_Spike_22.mirror = true;
      setRotation(Back_Spike_21, 0F, 0F, 0F);
      Back_Spike_23 = new ModelRenderer(this, 0, 0);
      Back_Spike_23.addBox(0F, 0F, 0F, 2, 2, 2);
      Back_Spike_23.setRotationPoint(5F, 17F, -1F);
      Back_Spike_23.setTextureSize(64, 32);
      Back_Spike_23.mirror = true;
      setRotation(Back_Spike_21, 0F, 0F, 0F);
  }
  
  public void render(float f5)
  {
    Back_Spike_21.render(f5);
    Base_1.render(f5);
    Base_2.render(f5);
    Stand.render(f5);
    Main_Section.render(f5);
    Front_Spike_1.render(f5);
    Front_Spike_2.render(f5);
    Back_Spike_21.render(f5);
    Back_Spike_21.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  

}
